version: '3.8'

services:
  scheduler:
    build: .
    container_name: batch
    hostname: batch
    ports:
      - "9000:8080"
    environment:
      - SERVICES=lambda
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - ENV=dev
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=

    volumes:
      - ./:/tmp